extends Node
## EventBus — global signal hub. No state, no logic. See docs/SPEC.md §3.

signal cash_changed(new_value)
signal gems_changed(new_value: int)
signal insight_changed(new_value)
signal reputation_changed(level: int, xp)
signal reputation_level_up(level: int, rewards: Dictionary)
signal department_upgraded(venue_id: String, dept_id: String, track: String, level: int)
signal cash_served(amount)
signal cash_banked(amount)
signal manual_collect(amount)
signal manager_obtained(manager_id: String, cards_gained: int)
signal manager_leveled(manager_id: String, level: int)
signal manager_ranked_up(manager_id: String, rank: int)
signal manager_assigned(manager_id: String, dept_id: String)
signal manager_exchanged(from_id: String, to_id: String, cards_spent: int, cards_gained: int)
signal lootbox_opened(box_id: String, results: Dictionary)
signal quest_completed(quest_id: String)
signal milestone_completed(venue_id: String, milestone_id: String)
signal venue_progress_changed(venue_id: String, progress: float)
signal prestige_available(venue_id: String)
signal prestige_performed(from_venue: String, to_venue: String)
signal decor_purchased(venue_id: String, decor_id: String)
signal unlock_changed(feature: String, unlocked: bool)
signal offline_earnings_ready(amount, seconds: int, was_capped: bool)
signal boost_changed(multiplier: float, seconds_remaining: int)
signal rv_reward_granted(placement_id: String, context: Dictionary)
signal iap_completed(product_id: String)
signal daily_deals_refreshed()
signal event_stage_completed(event_id: String, stage_index: int, rewards: Dictionary)
signal insight_storage_changed(stored, cap)
signal toast_requested(text: String)
signal clock_anomaly(kind: String)
