extends Node
## PlatformServices — the one door to whichever storefront this build ships on.
##
## Game code calls this, never a store SDK: unlock achievements, report stats,
## and (later) cloud saves and the overlay. The backend is chosen at runtime:
##   "steam"        GodotSteam GDExtension present (Engine singleton "Steam");
##                  builds exported from the Steam presets carry the "steam"
##                  feature tag.
##   "epic"         an EOS plugin singleton ("EOS" / "IEOS") on "epic" builds.
##   "play_games"   Android with the Google Play Games Services plugin
##                  (singleton "GodotPlayGameServices").
##   "game_center"  iOS with Godot's official GameCenter plugin (singleton
##                  "GameCenter"), which answers through a polled event queue.
##   "none"         everything else (Microsoft Store, dev runs): achievements
##                  are still tracked and saved locally, so wiring a store later
##                  back-fills what the player already earned.
## Store SDK calls go through call() on the singleton, so this script compiles
## and runs without any plugin installed. docs/PLATFORMS.md has the setup.
##
## Mobile accounts sign in asynchronously, so nothing is mirrored until the
## store says the player is signed in; then everything earned so far is sent
## at once (both stores ignore an achievement that's already unlocked). Play
## Games ids are generated by the Play Console, so they're mapped in
## data/achievements.json "platform_ids"; Game Center uses our ids (with an
## optional prefix) unless mapped there too.
##
## Achievements are data (data/achievements.json): each names the EventBus
## signal that re-checks it and a counter; counters derive from game state
## where possible and only "upgrades" is counted here.

signal achievement_unlocked(id: String, def: Dictionary)
signal signed_in_changed(signed_in: bool)

const PLAY_GAMES_SINGLETON := "GodotPlayGameServices"
const GAME_CENTER_SINGLETON := "GameCenter"

var backend := "none"
## True once the storefront account can take achievements (PC stores: at
## init; mobile: after the store reports a sign-in).
var signed_in := false
var _store: Object = null
var _defs: Array = []
var _platform_ids: Dictionary = {}

func _ready() -> void:
	_defs = _load_defs()
	_detect_backend()
	var signals := {}
	for d in _defs:
		signals[str(d.get("on", ""))] = true
	for sig in signals.keys():
		if sig != "" and EventBus.has_signal(sig):
			EventBus.connect(sig, _on_event.unbind(_arg_count(sig)))
	# Counters only events can know.
	EventBus.department_upgraded.connect(func(_v: String, _d: String, _t: String, _l: int) -> void: _bump("upgrades"))
	EventBus.item_upgraded.connect(func(_v: String, _d: String, _i: int, _l: int) -> void: _bump("upgrades"))
	EventBus.vip_tipped.connect(func(type_id: String, _amount: Variant) -> void:
		if type_id == "royal":
			_bump("royal_tips")
		_bump("vip_tips"))
	# Catch up once the save is loaded (and mirror to a newly attached store).
	var t := get_tree().create_timer(2.0)
	t.timeout.connect(func() -> void:
		check_all()
		sync_store())

func _arg_count(sig: String) -> int:
	for s in EventBus.get_signal_list():
		if str(s["name"]) == sig:
			return (s["args"] as Array).size()
	return 0

func _load_defs() -> Array:
	var f := FileAccess.open("res://data/achievements.json", FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if not parsed is Dictionary:
		return []
	_platform_ids = (parsed as Dictionary).get("platform_ids", {})
	return (parsed as Dictionary).get("achievements", [])

func _detect_backend() -> void:
	if Engine.has_singleton("Steam") and (OS.has_feature("steam") or OS.has_feature("editor")):
		_store = Engine.get_singleton("Steam")
		var ok := true
		if _store.has_method("steamInitEx"):
			var res: Variant = _store.call("steamInitEx", false)
			ok = res is Dictionary and int((res as Dictionary).get("status", 1)) == 0
		elif _store.has_method("steamInit"):
			_store.call("steamInit")
		backend = "steam" if ok else "none"
	elif OS.has_feature("epic"):
		for name in ["EOS", "IEOS"]:
			if Engine.has_singleton(name):
				_store = Engine.get_singleton(name)
				backend = "epic"
				break
	elif Engine.has_singleton(PLAY_GAMES_SINGLETON):
		_bind_play_games(Engine.get_singleton(PLAY_GAMES_SINGLETON))
	elif Engine.has_singleton(GAME_CENTER_SINGLETON):
		_bind_game_center(Engine.get_singleton(GAME_CENTER_SINGLETON))
	if backend == "none":
		_store = null
	signed_in = backend == "steam" or backend == "epic"

## Play Games v2 signs the player in by itself at launch; isAuthenticated()
## asks for the answer, which arrives on userAuthenticated.
func _bind_play_games(obj: Object) -> void:
	_store = obj
	backend = "play_games"
	signed_in = false
	if obj.has_method("initialize"):
		obj.call("initialize")
	if obj.has_signal("userAuthenticated") and not obj.is_connected("userAuthenticated", _on_sign_in):
		obj.connect("userAuthenticated", _on_sign_in)
	if obj.has_method("isAuthenticated"):
		obj.call("isAuthenticated")

## Game Center shows its own sign-in sheet if needed; the answer is an
## "authentication" event in the queue _process drains.
func _bind_game_center(obj: Object) -> void:
	_store = obj
	backend = "game_center"
	signed_in = false
	if obj.has_method("authenticate"):
		obj.call("authenticate")

func _on_sign_in(ok: bool) -> void:
	var was := signed_in
	signed_in = ok
	Analytics.log_event("platform_sign_in", {"backend": backend, "ok": ok})
	if ok != was:
		signed_in_changed.emit(ok)
	if ok:
		sync_store()

## Test seam: attach a fake store object as a mobile backend.
func _use_store_for_test(kind: String, obj: Object) -> void:
	if kind == "play_games":
		_bind_play_games(obj)
	elif kind == "game_center":
		_bind_game_center(obj)

## Test seam: back to the offline backend.
func _clear_store_for_test() -> void:
	if _store != null and _store.has_signal("userAuthenticated") and _store.is_connected("userAuthenticated", _on_sign_in):
		_store.disconnect("userAuthenticated", _on_sign_in)
	backend = "none"
	_store = null
	signed_in = false

func _process(_delta: float) -> void:
	if _store == null:
		return
	if backend == "steam" and _store.has_method("run_callbacks"):
		_store.call("run_callbacks")
	elif backend == "game_center":
		_poll_game_center()

func _poll_game_center() -> void:
	if not _store.has_method("get_pending_event_count"):
		return
	var guard := 0
	while int(_store.call("get_pending_event_count")) > 0 and guard < 32:
		guard += 1
		var ev: Variant = _store.call("pop_pending_event")
		if ev is Dictionary and str((ev as Dictionary).get("type", "")) == "authentication":
			_on_sign_in(str((ev as Dictionary).get("result", "")) == "ok")

# ----------------------------------------------------------------- achievements

func definitions() -> Array:
	return _defs

func unlocked() -> Array:
	return _state().get("unlocked", [])

func is_unlocked(id: String) -> bool:
	return id in unlocked()

func _state() -> Dictionary:
	var s: Dictionary = GameState.achievements_state
	if not s.has("unlocked"):
		s["unlocked"] = []
		s["counters"] = {}
	return s

func _bump(counter: String) -> void:
	var c: Dictionary = _state()["counters"]
	c[counter] = int(c.get(counter, 0)) + 1
	check_all()

func _on_event() -> void:
	check_all()

## Current value of an achievement counter, derived from game state.
func counter(name: String) -> int:
	match name:
		"milestones":
			var n := 0
			for vs in GameState.venues_state.values():
				n += (vs as Dictionary).get("milestones", []).size()
			return n
		"wings":
			var w := 0
			for vs in GameState.venues_state.values():
				w += (vs as Dictionary).get("wings", []).size()
			return w
		"best_grandeur":
			var best := 1
			for vs in GameState.venues_state.values():
				best = maxi(best, 1 + (vs as Dictionary).get("wings", []).size())
			return best
		"artifacts", "perfect_artifacts", "sets":
			var col: Dictionary = GameState.dig_state.get("collection", {})
			var total := 0
			var perfect := 0
			var sets := 0
			for vid in col.keys():
				var arts: Dictionary = col[vid]
				total += arts.size()
				for q in arts.values():
					if int(q) >= 3:
						perfect += 1
				if arts.size() >= 5:
					sets += 1
			return {"artifacts": total, "perfect_artifacts": perfect, "sets": sets}[name]
		"museums":
			return GameState.venues_unlocked.size()
		"managers":
			var m := 0
			for st in GameState.managers_state.values():
				if int((st as Dictionary).get("cards", 0)) > 0 or str((st as Dictionary).get("assigned_to", "")) != "":
					m += 1
			return m
		"rep":
			return GameState.rep_level()
		"gifts":
			return int((GameState.event_state.get("daily_gifts", {}) as Dictionary).get("total", 0))
	return int((_state()["counters"] as Dictionary).get(name, 0))

func check_all() -> void:
	if not GameState.ready_flag:
		return
	for d in _defs:
		var id := str(d.get("id", ""))
		if id == "" or is_unlocked(id):
			continue
		if counter(str(d.get("count", ""))) >= int(d.get("need", 1)):
			unlock(id)

## Record an achievement and mirror it to the storefront.
func unlock(id: String) -> void:
	if is_unlocked(id):
		return
	(_state()["unlocked"] as Array).append(id)
	var def := {}
	for d in _defs:
		if str(d.get("id", "")) == id:
			def = d
	_mirror(id, true)
	if backend == "steam" and signed_in:
		_store.call("storeStats")
	achievement_unlocked.emit(id, def)
	EventBus.toast_requested.emit("Achievement: %s" % str(def.get("name", id)))
	Analytics.log_event("achievement", {"id": id, "backend": backend})

## Resync every locally earned achievement to the store (first launch on a new
## storefront, or after the player earned some offline).
func sync_store() -> void:
	if backend == "none" or _store == null or not signed_in:
		return
	for id in unlocked():
		_mirror(str(id), false)
	if backend == "steam":
		_store.call("storeStats")

## The storefront's id for one of ours: Play Games needs a mapping from the
## Play Console; Game Center and the PC stores use ours unless mapped.
func platform_id(id: String) -> String:
	var mapped: Dictionary = _platform_ids.get(backend, {})
	if mapped.has(id):
		return str(mapped[id])
	match backend:
		"play_games":
			return ""
		"game_center":
			return str(_platform_ids.get("game_center_prefix", "")) + id
	return id

## Send one unlocked achievement to the storefront. `fresh` is a new unlock
## (Game Center shows its banner); a sync of old ones stays quiet.
func _mirror(id: String, fresh: bool) -> void:
	if backend == "none" or _store == null or not signed_in:
		return
	var pid := platform_id(id)
	if pid == "":
		return
	match backend:
		"steam":
			_store.call("setAchievement", pid)
		"epic":
			if _store.has_method("unlock_achievement"):
				_store.call("unlock_achievement", pid)
		"play_games":
			_store.call("unlockAchievement", pid)
		"game_center":
			_store.call("award_achievement", {"name": pid, "progress": 100.0, "show_completion_banner": fresh})

## True when the storefront has its own achievements screen to open.
func can_show_platform_achievements() -> bool:
	if _store == null or not signed_in:
		return false
	match backend:
		"play_games":
			return _store.has_method("showAchievements")
		"game_center":
			return _store.has_method("show_game_center")
		"steam":
			return _store.has_method("activateGameOverlay")
	return false

## Open the storefront's achievements screen (Play Games, Game Center, the
## Steam overlay). Returns false when there's none to open.
func show_platform_achievements() -> bool:
	if not can_show_platform_achievements():
		return false
	match backend:
		"play_games":
			_store.call("showAchievements")
		"game_center":
			_store.call("show_game_center", {"view": "achievements"})
		"steam":
			_store.call("activateGameOverlay", "achievements")
	return true
